### ISSUE TITLE
Multiple version of react

### ISSUE THREAD

**Issue by endurance21** [endurance21/firefly-react#1]
We are using react and react-dom internally, when imported by other project this same react and reac-dom must not be used by any code in src/ folder as this would result  [this issue ] (https://github.com/facebook/react/issues/13991) , so we need to do something called peerDependecy thing so that this library used the React of project which is importing this repo not react present in  this particular repo.

**Comment by Adi-11** [comment]
https://github.com/endurance21/firefly-react/pull/2

fixed
